#:schema node_modules/wrangler/config-schema.json
name = "walksafe"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "walksafe-db"
database_id = "fc5c7200-1e11-40cf-a38f-c7b0b4884b69"

[triggers]
crons = ["30 7 * * *"]
